export const UI_TEXT = {
  app: {
    title: "AgentOps 控制台",
    stage: "阶段三最小可用版",
    navigationLabel: "控制台导航",
    subtitle: "Agent 运行、观测与治理底座",
    searchPlaceholder: "搜索请求链路、任务或告警",
    environment: "开发环境"
  },
  nav: {
    overview: "控制台首页",
    traces: "请求链路",
    traceDetail: "请求链路详情",
    taskDetail: "任务详情",
    observability: "观测面板",
    running: "运行与观测",
    capability: "能力配置",
    settings: "系统设置",
    taskManagement: "任务管理",
    alertCenter: "告警中心",
    agents: "Agent 管理",
    tools: "工具管理",
    modelsAndRouting: "模型与路由",
    permissions: "权限管理",
    auditLogs: "审计日志"
  },
  action: {
    search: "查询",
    reset: "重置",
    retry: "重试",
    viewFullContent: "查看完整内容",
    previousPage: "上一页",
    nextPage: "下一页",
    backToTraceList: "返回请求链路列表",
    openTaskDetail: "查看任务详情",
    openTraceDetail: "查看请求链路",
    login: "进入控制台"
  },
  common: {
    all: "全部",
    yes: "是",
    no: "否",
    loading: "加载中",
    noPermission: "无访问权限",
    loadFailed: "加载失败",
    noResults: "无匹配结果"
  },
  field: {
    trace: "请求链路",
    traceId: "请求链路编号",
    requestId: "请求编号",
    task: "任务",
    taskId: "任务编号",
    sessionId: "会话编号",
    turnId: "轮次编号",
    method: "请求方法",
    path: "请求路径",
    methodPath: "方法 / 路径",
    status: "状态",
    statusCode: "状态码",
    startTime: "开始时间",
    updateTime: "更新时间",
    route: "路由",
    routeName: "路由名称",
    routeSource: "路由来源",
    execution: "执行",
    executionMode: "执行模式",
    review: "评审",
    reviewStatus: "评审状态",
    alert: "告警",
    errorCode: "错误码",
    errorMessage: "错误信息",
    rateLimited: "是否限流",
    exitCode: "退出码",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    userInput: "用户输入",
    answer: "回复",
    toolCount: "工具数量",
    source: "来源",
    decisions: "决策数",
    traceCount: "请求数",
    alertCount: "告警数",
    severity: "严重级别",
    lastTask: "最近任务",
    lastTrace: "最近请求链路",
    lastDecidedAt: "最近决策时间",
    lastUpdatedAt: "最近更新时间",
    lastStartedAt: "最近开始时间",
    lastCreatedAt: "最近创建时间"
  },
  page: {
    traceListTitle: "请求链路列表",
    traceListSubtitle: "请求链路查询视图。",
    traceDetailTitle: "请求链路详情",
    taskDetailTitle: "任务详情",
    observabilityTitle: "观测面板",
    observabilitySubtitle: "全局运行时视图。",
    taskDetailSubtitle: "任务执行摘要与关联请求链路。"
  },
  hint: {
    traceList: "可按请求链路、任务、路径、状态码或路由筛选记录；点击请求链路编号进入详情。",
    traceDetail: "用于查看单次请求链路的概览、时间线、工具结果、告警和链路结构；如关联任务存在，可跳转任务详情。",
    taskDetail: "用于查看任务摘要、执行状态、事件记录和关联请求链路。",
    observability: "用于查看运行时、任务、请求链路、告警和路由决策的聚合概览。"
  },
  shell: {
    productName: "AgentOps",
    productSubtitle: "运行控制台",
    footer: "© 2026 AgentOps | 版本 v1.0.0 | 备案号：待备案",
    userName: "控制台管理员",
    userRole: "运维控制台",
    profile: "个人中心",
    accountSettings: "账号设置",
    preferences: "系统偏好",
    switchEnvironment: "切换环境",
    logout: "退出登录"
  },
  login: {
    title: "登录 AgentOps",
    subtitle: "请输入账号信息，进入 AI Agent 后台管理系统。",
    brandTitle: "AgentOps",
    brandDescription: "AI Agent 后台管理系统，统一管理任务执行、请求链路观测、Agent 配置、工具能力、模型路由与系统设置。",
    capabilityTask: "任务执行管理：管理任务状态、执行结果、重试记录和运行耗时，为异步任务流转提供基础。",
    capabilityTrace: "请求链路排障：查看 plan、tool、answer 等节点执行链路，快速定位错误与 token 热点。",
    capabilityGovernance: "工具与模型配置：集中管理 OCR、搜索、数据库等工具，以及模型与路由策略。",
    accountLabel: "账号",
    passwordLabel: "密码",
    accountPlaceholder: "admin@agentops.local",
    passwordPlaceholder: "请输入密码",
    environmentHint: "当前环境：开发环境",
    rememberLogin: "记住登录状态",
    forgotPassword: "忘记密码",
    formHint: "后续可扩展：验证码、单点登录、租户入口、登录失败提示、环境切换提示。",
    positioning: "当前定位：后台系统入口，不是营销官网。风格基调：稳、清晰、专业，具备平台感。"
  },
  state: {
    loadingTraceList: "正在加载请求链路列表。",
    loadingTraceDetail: "正在加载请求链路详情。",
    traceListNoPermission: "当前账号无权访问请求链路列表。",
    traceDetailNoPermission: "当前账号无权查看该请求链路。",
    traceListLoadFailed: "请求链路列表加载失败。",
    traceDetailLoadFailed: "请求链路详情加载失败。",
    traceRecordMissing: "该请求链路记录不存在或已不可用，请返回列表或观测面板选择其他记录。",
    staleTraceReferenceHint: "部分关联请求链路可能已不可用，打开后如提示记录不存在，请返回当前页面继续查看其他记录。",
    missingTraceId: "缺少请求链路编号。",
    missingTaskId: "缺少任务编号。",
    loadingTaskSummary: "正在加载任务摘要。",
    taskNoPermission: "当前账号无权查看该任务。",
    taskSummaryLoadFailed: "任务摘要加载失败。",
    taskNotFound: "未找到任务",
    noTaskSummary: "当前任务暂无可用摘要。",
    loadingOperationsOverview: "正在加载运行概览。",
    operationsNoPermission: "当前账号无权查看运行概览。",
    operationsOverviewLoadFailed: "运行概览加载失败。",
    noRecentData: "暂无近期数据",
    noRecentActivity: "运行概览已加载，但暂无近期活动。",
    noTraces: "暂无请求链路",
    noTraceRecords: "暂无可展示的请求链路记录。",
    adjustFilters: "请调整筛选条件后重试。",
    noLinkedTaskSummary: "当前请求链路没有关联任务摘要。",
    noTimelineEvents: "暂无时间线事件。",
    noTaskEventsOrToolResults: "暂无任务事件或工具结果。",
    noTaskEvents: "暂无任务事件。",
    noRelatedTrace: "无关联请求链路",
    noRelatedRequestTrace: "暂无关联请求链路。",
    noAlerts: "暂无告警。",
    noRecentAlerts: "运行概览已加载，但暂无近期告警。",
    noRecentTasks: "运行概览已加载，但暂无近期任务。",
    noRouteStats: "运行概览已加载，但暂无路由统计数据。",
    noTaskStatusStats: "运行概览已加载，但暂无任务状态数据。",
    noTraceStats: "运行概览已加载，但暂无请求链路流量统计数据。",
    noAlertStats: "运行概览已加载，但暂无告警聚合统计数据。",
    noStructureNodes: "暂无结构节点。",
    noStructureEdges: "暂无结构边。"
  },
  panel: {
    overview: "概览",
    traceOverview: "请求链路概览",
    taskOverview: "任务概览",
    status: "状态",
    taskStatus: "任务状态",
    statusSummary: "状态摘要",
    linkedTask: "关联任务",
    noLinkedTask: "无关联任务",
    relatedTrace: "关联请求链路",
    events: "事件",
    taskEvents: "任务事件",
    timeline: "时间线",
    eventTimeline: "事件时间线",
    consoleLogs: "控制台日志",
    taskEventsAndToolResults: "任务事件与工具结果",
    alerts: "告警",
    alertEvents: "告警事件",
    alertSummary: "告警摘要",
    recentAlerts: "近期告警",
    recentActivity: "近期活动",
    recentTasks: "近期任务",
    traceTrafficStats: "请求链路流量统计",
    traceTraffic: "请求流量",
    alertStats: "告警统计",
    alertAggregation: "告警聚合",
    routeStats: "路由统计",
    routingDecisions: "路由决策",
    graph: "链路结构",
    simpleStructure: "基础结构",
    nodes: "节点",
    edges: "边"
  },
  status: {
    pass: "通过",
    fail: "失败",
    success: "成功",
    failed: "失败",
    critical: "严重",
    error: "错误",
    warning: "警告",
    rateLimited: "已限流"
  },
  statusLabel: {
    completed: "已完成",
    success: "成功",
    succeeded: "成功",
    done: "已完成",
    failed: "失败",
    error: "错误",
    cancelled: "已取消",
    running: "运行中",
    pending: "等待中",
    retrying: "重试中",
    pass: "通过",
    fail: "失败",
    critical: "严重",
    warning: "警告"
  },
  observability: {
    activeTasks: "活跃任务",
    maxWorkers: "最大工作线程",
    activeTaskIds: "活跃任务编号",
    recentTasks: "近期任务",
    recentAlerts: "近期告警",
    totalTraces: "请求总数",
    estimatedSuccessRate: "请求成功率（估算）",
    errorTraces: "错误请求数",
    rateLimitedTraces: "限流请求数",
    currentRuntimeActiveCount: "当前运行时活跃数量",
    configuredWorkerCapacity: "已配置工作线程容量",
    fromOperationsOverview: "来自运行概览",
    fromTraceStats: "来自请求链路统计"
  },
  pagination: {
    summary: (start: number, end: number, total: number) => `显示第 ${start}-${end} 条，共 ${total} 条`,
    structureCount: (nodes: number, edges: number) => `${nodes} 个节点 / ${edges} 条边`
  }
} as const;
